version: '3'
services:
  web:
    build: .
    env_file: .env
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.services.codelabs_progress.loadbalancer.server.port=8080"
      - "traefik.http.routers.codelabs_progress.rule=Host(`codelabs.bf0.ch`)"
      - "traefik.http.routers.codelabs_progress.entrypoints=web"
      - "traefik.http.routers.codelabs_progress.middlewares=https_redirect"
      - "traefik.http.routers.codelabs_progress_secured.rule=Host(`codelabs.bf0.ch`)"
      - "traefik.http.routers.codelabs_progress_secured.entrypoints=websecure"
      - "traefik.http.routers.codelabs_progress_secured.tls=true"
      - "traefik.http.routers.codelabs_progress_secured.tls.certresolver=myresolver"
    volumes:
      - db-data:/app/db
    networks:
      - web
      - default
volumes:
   db-data:
     driver: local
networks:
  web:
    external: true